# Generated by Django 2.0.5 on 2020-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='manage',
            new_name='owner',
        ),
    ]
